// TaskFlow.Web/src/components/KanbanColumn.vue
<script setup lang="ts">
import { ref } from 'vue';
import type { Task } from '../stores/taskStore';
import TaskCard from './TaskCard.vue';
import { useDroppable } from '@dnd-kit/vue';

const props = defineProps<{
  title: string;
  status: number;
  tasks: Task[];
}>();

const emit = defineEmits<{
  (e: 'task-click', task: Task): void;
  (e: 'add-task', status: number): void;
}>();

const columnElement = ref<HTMLElement | null>(null);
const { isDropTarget } = useDroppable({
  id: `column-${props.status}`,
  element: columnElement
});
</script>

<template>
  <div
    ref="columnElement"
    class="flex flex-col flex-shrink-0 w-80 bg-gray-50 rounded-xl p-3 border border-gray-200 shadow-sm h-full"
    :class="{
      'ring-2 ring-blue-400 ring-offset-2 ring-offset-slate-50': isDropTarget
    }"
  >
    <div class="flex items-center justify-between mb-3 px-1">
      <h3 class="font-semibold text-gray-700 flex items-center gap-2">
        {{ title }}
        <span class="bg-gray-200 text-gray-600 text-xs px-2 py-0.5 rounded-full font-medium">
          {{ tasks.length }}
        </span>
      </h3>
      <button 
        @click="emit('add-task', status)"
        class="text-gray-400 hover:text-gray-600 p-1 rounded hover:bg-gray-200 transition-colors"
      >
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" clip-rule="evenodd" />
        </svg>
      </button>
    </div>

    <div
      class="flex-1 overflow-y-auto min-h-0 custom-scrollbar space-y-3 p-1"
    >
      <TaskCard 
        v-for="task in tasks" 
        :key="task.id" 
        :task="task"
        @click="emit('task-click', task)"
      />
      
      <div v-if="tasks.length === 0" class="h-24 border-2 border-dashed border-gray-300 rounded-lg flex items-center justify-center text-gray-400 text-sm">
        Drag tasks here
      </div>
    </div>
  </div>
</template>

<style scoped>
.custom-scrollbar::-webkit-scrollbar {
  width: 6px;
}
.custom-scrollbar::-webkit-scrollbar-track {
  background: transparent;
}
.custom-scrollbar::-webkit-scrollbar-thumb {
  background-color: #cbd5e1;
  border-radius: 20px;
}
</style>

// TaskFlow.Web/src/components/Task/KanbanColumn.tsx
import { useDroppable } from '@dnd-kit/core';
import { SortableContext, verticalListSortingStrategy } from '@dnd-kit/sortable';
import { Plus } from 'lucide-react';
import type { Task } from '../../types';
import TaskCard from './TaskCard';

interface Props {
  id: number;
  title: string;
  tasks: Task[];
  onTaskClick: (task: Task) => void;
  onAddTask: (status: number) => void;
}

const COLUMN_COLORS: Record<number, string> = {
  0: 'bg-base-content/5',
  1: 'bg-info/5',
  2: 'bg-warning/5',
  3: 'bg-success/5',
};

export default function KanbanColumn({ id, title, tasks, onTaskClick, onAddTask }: Props) {
  const { setNodeRef, isOver } = useDroppable({ id: String(id) });

  return (
    <div className="flex-shrink-0 w-72 flex flex-col">
      {/* Header */}
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <span className="text-sm font-semibold text-base-content">{title}</span>
          <span className="inline-flex items-center justify-center min-w-[20px] h-5 px-1.5 rounded-full bg-base-300 text-[10px] font-semibold text-base-content/70">
            {tasks.length}
          </span>
        </div>
        <button
          onClick={() => onAddTask(id)}
          className="p-1 rounded-lg hover:bg-base-300 text-base-content/50 hover:text-base-content transition-colors"
          title="Add task"
        >
          <Plus className="w-4 h-4" />
        </button>
      </div>

      {/* Cards */}
      <div
        ref={setNodeRef}
        className={`flex-1 min-h-[120px] rounded-xl p-2 transition-colors space-y-2 ${COLUMN_COLORS[id]} ${isOver ? 'ring-2 ring-primary/40' : ''}`}
      >
        <SortableContext items={tasks.map((t) => t.id)} strategy={verticalListSortingStrategy}>
          {tasks.map((task) => (
            <TaskCard key={task.id} task={task} onClick={onTaskClick} />
          ))}
        </SortableContext>
      </div>
    </div>
  );
}
