// TaskFlow.Web/src/components/Notification/NotificationsPanel.tsx
import { useEffect, useRef } from 'react';
import { X, CheckCheck, Bell } from 'lucide-react';
import { useNotificationStore } from '../../stores/notificationStore';
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';

dayjs.extend(relativeTime);

interface Props { onClose: () => void; }

export default function NotificationsPanel({ onClose }: Props) {
  const { notifications, markAsRead, markAllAsRead } = useNotificationStore();
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) onClose();
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [onClose]);

  return (
    <div
      ref={ref}
      className="absolute bottom-full left-0 mb-2 w-80 bg-base-100 border border-base-300 rounded-xl shadow-xl z-50"
    >
      <div className="flex items-center justify-between px-4 py-3 border-b border-base-300">
        <span className="font-semibold text-sm text-base-content">Notifications</span>
        <div className="flex items-center gap-1">
          <button
            onClick={markAllAsRead}
            className="p-1.5 rounded hover:bg-base-200 text-base-content/60 hover:text-base-content transition-colors"
            title="Mark all as read"
          >
            <CheckCheck className="w-4 h-4" />
          </button>
          <button
            onClick={onClose}
            className="p-1.5 rounded hover:bg-base-200 text-base-content/60 hover:text-base-content transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>
      </div>

      <div className="max-h-80 overflow-y-auto">
        {notifications.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-8 text-base-content/40">
            <Bell className="w-8 h-8 mb-2" />
            <p className="text-sm">No notifications</p>
          </div>
        ) : (
          notifications.map((n) => (
            <button
              key={n.id}
              onClick={() => !n.isRead && markAsRead(n.id)}
              className={`w-full text-left px-4 py-3 border-b border-base-200 hover:bg-base-200 transition-colors last:border-0 ${
                n.isRead ? 'opacity-60' : ''
              }`}
            >
              <div className="flex items-start gap-2">
                {!n.isRead && <span className="w-2 h-2 rounded-full bg-primary mt-1.5 flex-shrink-0" />}
                <div className={n.isRead ? 'ml-4' : ''}>
                  <p className="text-xs text-base-content leading-relaxed">{n.message}</p>
                  <p className="text-[10px] text-base-content/40 mt-0.5">{dayjs(n.createdAt).fromNow()}</p>
                </div>
              </div>
            </button>
          ))
        )}
      </div>
    </div>
  );
}

// TaskFlow.Web/src/components/NotificationsPanel.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import { useNotificationStore } from '../stores/notificationStore';

const notificationStore = useNotificationStore();

const emit = defineEmits<{
  (e: 'close'): void;
}>();

onMounted(async () => {
  await notificationStore.fetchNotifications(true);
});

const formatTime = (iso: string) => {
  const date = new Date(iso);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffMin = Math.floor(diffMs / 60000);
  if (diffMin < 1) return 'just now';
  if (diffMin < 60) return `${diffMin}m ago`;
  const diffH = Math.floor(diffMin / 60);
  if (diffH < 24) return `${diffH}h ago`;
  return date.toLocaleDateString();
};

const handleMarkAsRead = async (id: string) => {
  await notificationStore.markAsRead(id);
};

const handleMarkAllRead = () => {
  notificationStore.markAllAsReadLocal();
};
</script>

<template>
  <div class="absolute bottom-full left-0 mb-2 w-80 bg-base-100 border border-base-300 rounded-xl shadow-xl z-50 overflow-hidden">
    <!-- Header -->
    <div class="flex items-center justify-between px-4 py-3 border-b border-base-200">
      <h3 class="text-sm font-semibold text-base-content">Notifications</h3>
      <div class="flex items-center gap-2">
        <button
          v-if="notificationStore.hasUnread"
          type="button"
          @click="handleMarkAllRead"
          class="text-xs text-primary hover:text-primary/80 font-medium"
        >
          Mark all read
        </button>
        <button type="button" @click="emit('close')" class="text-base-content/50 hover:text-base-content/70">
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
          </svg>
        </button>
      </div>
    </div>

    <!-- List -->
    <div class="max-h-72 overflow-y-auto">
      <div v-if="notificationStore.loading" class="flex justify-center py-6">
        <div class="animate-spin rounded-full h-5 w-5 border-b-2 border-primary"></div>
      </div>

      <div v-else-if="!notificationStore.items.length" class="py-8 text-center text-sm text-base-content/50">
        No notifications yet
      </div>

      <div v-else>
        <div
          v-for="notif in notificationStore.items"
          :key="notif.id"
          :class="[
            'px-4 py-3 border-b border-base-200 last:border-0 transition-colors hover:bg-base-200 cursor-pointer',
            !notif.isRead ? 'bg-primary/10' : ''
          ]"
          @click="!notif.isRead && handleMarkAsRead(notif.id)"
        >
          <div class="flex items-start gap-2.5">
            <span
              :class="['w-2 h-2 rounded-full mt-1.5 flex-shrink-0', !notif.isRead ? 'bg-primary' : 'bg-transparent']"
            ></span>
            <div class="flex-1 min-w-0">
              <p class="text-sm text-base-content leading-snug">{{ notif.message }}</p>
              <p class="text-xs text-base-content/50 mt-0.5">{{ formatTime(notif.createdAt) }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
